name: euro-spores
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.7
    - flake8=3.7.8
    - pycountry=18.12.8
    - snakemake-minimal=5.8.2
    - numpy=1.17.2
    - pandas=0.25.1
    - xarray=0.14.1
    - netcdf4=1.5.3
    - gdal=2.4
    - libtiff=4.0.10
    - geopandas=0.5.0
    - descartes=1.1.0
    - matplotlib=3.1.2
    - seaborn=0.10.0
    - python-ternary=1.0.6
    - jinja2=2.10.1
    - salib=1.1.2
    - xlrd=1.1.0
    - pip:
        - pyxlsb==1.0.6
