name: euro-spores
channels:
    - conda-forge
    - bioconda
dependencies:
    - python>=3.7
    - flake8
    - pycountry=19.8
    - snakemake-minimal=5.19
    - numpy
    - pandas
    - xarray
    - netcdf4
    - gdal=2.4
    - libtiff
    - geopandas
    - descartes
    - matplotlib
    - seaborn
    - python-ternary
    - jinja2
    - salib
    - xlrd
