cluster: bsub -oo {cluster.output} -W {cluster.runtime} -n {cluster.cores} -R "rusage[mem={cluster.memory}, scratch={cluster.scratch}]" -J {cluster.name} <
jobs: 999
cluster-config: "config/euler/cluster-config.yaml"
local-cores: 1
latency-wait: 60
