name: default
channels:
    - conda-forge
dependencies:
    - python=3.7
    - numpy=1.17.2
    - pandas=0.25.1
    - xarray=0.14.1
    - netcdf4=1.5.3
    - descartes=1.1.0
    - matplotlib=3.1.2
    - seaborn=0.10.0
    - python-ternary=1.0.6
    - jinja2=2.10.1
    - salib=1.1.2
    - xlrd=1.1.0