name: default
channels:
    - conda-forge
dependencies:
    - python=3.7
    - numpy=1.18.5
    - pandas=1.0.5
    - xarray=0.15.1
    - netcdf4=1.5.3
    - descartes=1.1.0
    - matplotlib=3.2.2
    - seaborn=0.10.1
    - xlrd=1.2.0
    - jinja2
    - pip=19.2.3
    - pip:
        - -e ../lib
